### ISSUE TITLE
Nav Display Bug

### ISSUE THREAD

**Issue by philsinatra** [vls48/php-portfolio#2]
1. Make the screen small
1. Click the hamburger to expose the navigation
1. Make the screen big

Navigation is hidden. You need to add some type of a listener in javascript for when the window resizes to make sure the navigation comes back on larger screens automatically.

**Comment by vls48** [comment]
I think this is going to be something I'm going to have to get help with during lab time- I spent a while looking into it but I can't quite get it, going to continue trying other solutions though

**Comment by philsinatra** [comment]
You have part of the right idea going [here](https://github.com/vls48/php-portfolio/blob/fca60c0be051b0d206d5681918a4171035fca9c0/source/main.js#L13-L15) when you listen for a resize. 

The next step is to indicate when you want to make changes based on the resizing. You can use the [`window.innerWidth` property](https://www.w3schools.com/jsref/prop_win_innerheight.asp) in an `if` statement to handle this.

<pre>
When the window is resized
  If the window inner width is < something 
    Do something
  Otherwise
    Do something else
</pre>

**Comment by philsinatra** [comment]
I made [a sample](https://codepen.io/philsinatra/pen/BZamxE) to help. Look this over and see if you can use it to guide you in your project. I'll help you in lab if needed.
