### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by philsinatra** [vls48/php-portfolio#5]
The floating navigation on small screens overlaps content on some screens. I think the UX and design would benefit from a fixed bar instead of a floating icon, in conjunction with a margin at the top of the page that pushes content below the bar on small screens, so there is no overlap of nav and content.

Also - the "HOME" button is broken on several pages.

**Comment by vls48** [comment]
Couldn't find which pages 'home' was broken on, you mean within the mobile nav specifically, correct?  Also- went with the full width bar, it def cleaned it up a lot!

**Comment by philsinatra** [comment]
Looks like this is working properly now.
